//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreezeRequests
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Type { get; set; }
        public Nullable<int> TargetId { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
